grails-app/domain/com/galleryofgood/gallery/Gallery.groovy
package com.galleryofgood.gallery

import com.galleryofgood.common.Flag
import com.galleryofgood.master.Base
import com.galleryofgood.common.Comment
import org.codehaus.groovy.grails.commons.ConfigurationHolder
import com.galleryofgood.common.UserFollow
import com.galleryofgood.security.AppUser

class Gallery{

    String id
    
    String owner
    String galleryName
    String description
    String artworkType
    String ownerYearOfBirth
    String galleryOwner="Myself"
    String galleryNameUrl

    String artisticJourney=""

    List youngArtists

    Date dateCreated
    Date lastUpdated

    static hasMany=[youngArtists:YoungArtist,
                    artworks:Artwork,timelines:Timeline,
                    flags:Flag
                    /*comments:com.galleryofgood.common.Comment*/]

    static mapping = {
        youngArtists cascade: 'all-delete-orphan'
        artworks cascade: 'all-delete-orphan'
        timelines cascade: 'all-delete-orphan'
        artworks sort: 'dateCreated', order: 'desc'
        version false
        id generator:'uuid'
    }

    static transients=['isForYoungArtist','followerCount'];

    boolean isForYoungArtist(){
        if (galleryOwner == "YoungArtist")
            return true;
        else
            return false;
    }
    

    static constraints = {
        ownerYearOfBirth(blank: true,nullable: true)
        galleryNameUrl(blank:false,nullable: false,unique:true,validator:galleryNameUrlValidator)
        galleryName(blank: false,nullable: false,unique:true, maxSize:255,validator: galleryNameValidator)
        description(maxSize:4000);
        galleryOwner(inList: ["Myself","YoungArtist"])
        galleryName validator: galleryNameValidator
        artworkType(inList: ["Drawing","Painting","Crafts","Mixed Media","Sculpture","Tinker Toys","Photography","Digital"])
        artisticJourney(blank: true,nullable: true,maxSize:4000)
        /*comments(lazy:false, cascade:"all,delete-orphan");*/
    }


    static final galleryNameValidator = { String galleryName, obj ->
        if (galleryName.matches('^.*[!@#$%^&].*$')) {
            return 'gallery.galleryName.specialCharacters.error'
        }
        if (galleryName.toLowerCase() in ConfigurationHolder.config.reservedNames||obj.galleryNameUrl.toLowerCase() in ConfigurationHolder.config.reservedNames){
            return 'gallery.galleryName.reserved.error'
        }
    }

    static final galleryNameUrlValidator = { val, obj ->
        if (val.matches('^.*[!@#$%^&].*$')) {
            return 'gallery.galleryName.specialCharacters.error'
        }
        if (val.toLowerCase() in ConfigurationHolder.config.reservedNames){
            return 'gallery.galleryName.reserved.error'
        }
    }


    def afterDelete(){
        Comment.withNewSession {
            try{
                Comment.findAllByLocationAndLocationId('Gallery', id)*.delete();
            }catch (Exception e){
                println(e);
            }
        }
        UserFollow.withNewSession {
            try{
                UserFollow.findAllByFollowingId(id)*.delete();
                UserFollow.findAllByFollowerId(AppUser.findByUsername(this.owner).id)*.delete();
            }catch (Exception e){
                println(e);
            }
        }
    }

    def getFollowerCount(){
        def totalFollowers = UserFollow.countByFollowingId(id)
        return totalFollowers
    }

    def getComments(){
        def comments = Comment.findAllByLocationAndLocationId("Gallery",id)
        return comments
    }

    String toString(){
        galleryName
    }
}

grails-app/views/layouts/_adminmenu.gsp
<sec:ifLoggedIn>
<div class="two columns ap-left">
    <div>
        <p>CONTENT</p>
        <hr />
        <a href="${createLink(controller:'admin',action:'homepage')}">Homepage</a>
        <hr />
        <a href="${createLink(controller:'admin',action:'artwork')}">Artworks</a>
        <hr />
        <a href="${createLink(controller:'advisor',action:'list')}">2cc</a>
        <hr />
        <a href="${createLink(controller:'admin',action:'comments')}">About Comments</a>
        <hr />
        %{----}%
        %{--<a href="#">Experiences</a>--}%
        %{--<hr />--}%
        %{--<a href="#">Fundraising</a>--}%
        %{--<hr />--}%
        <br />
        <br />
    </div>
    <div>
        <p>USERS</p>
        <hr />
        <a href="${createLink(controller:'admin',action:'listUsers')}">All Accounts</a>
        <hr />
        <a href="${createLink(controller:'admin',action:'listUsers', params:['page':'standard'], fragment: 'standardUser')}">Standard Account</a>
        <hr />
        <a href="${createLink(controller:'admin',action:'listUsers', params:['page':'newArtwork'], fragment: 'newArtwork')}">New Artworks</a>
        <hr />
        <a href="${createLink(controller:'admin',action:'listUsers', params:['page':'flagged'], fragment: 'flag')}">Flagged</a>
        <hr />
        <br />
        <br />
    </div>
    <div>
        <p>ADMIN</p>
        <hr />
        <a href="${createLink(controller:'admin',action:'listAdministrators')}">All Administrators</a>
        <hr />
        <a href="${createLink(controller:'admin',action:'listGalleries')}">All Galleries</a>
        <hr />
        <a href="${createLink(controller:'admin',action:'commentsAll')}">All Comments</a>
        <hr />
        <a href="${createLink(action: 'createAdmin',controller:'admin')}">Add Administrator</a>
        <hr />
        <a href="${createLink(action: 'yourProfile',controller:'admin')}">Your Profile</a>
        <hr />
        <br/>
        <br/>
    </div>
    <div>
        <p>ROLES</p>
        <hr/>
        <a href="${createLink(controller:'role',action:'search')}">Search</a>
        <hr/>
        <a href="${createLink(controller:'role',action:'create')}">Create</a>
        <hr/>
        <br/>
        <br/>
    </div>
    <div>
        <p>System Parameters</p>
        <hr/>
        <a href="${createLink(controller:'systemParameter',action:'editParameters')}">System Parameters</a>
        <hr/>
        <a href="${createLink(controller:'role',action:'create')}">Create</a>
        <hr/>
    </div>
</div>
</sec:ifLoggedIn>

grails-app/views/layouts/_flashErrors.gsp
<g:if test="${flash.errors}">
<div class="row">
    <div class="twelve columns">
    &nbsp;
            <div class="alert-box error">
                <g:each in="${flash.errors}" var="error">
                ${error}<br/>
                </g:each>
                <a href="" class="close">&times;</a>
            </div>
    </div>
</div>
</g:if>
<g:if test="${flash.error}">
    <div class="row">
        <div class="twelve columns">
            &nbsp;
            <div class="alert-box error">
                    ${flash.error}<br/>
                <a href="" class="close">&times;</a>
            </div>
        </div>
    </div>
</g:if>

grails-app/views/layouts/_flashMessage.gsp
<g:if test="${flash.message}">
<div class="row" id="messagealert">
    <div class="twelve columns">
            <div class="alert-box success">
                ${flash.message}
                <a href="" class="close">&times;</a>
            </div>
    </div>
</div>
<script type="text/javascript">
    $(function () {
        $("#messagealert").fadeOut(10000);
    });
</script>

</g:if>

grails-app/views/layouts/_flashWarning.gsp
<div class="row">
    <div class="twelve columns">
        <div id="warning" class="alert-box [success warning error]" style="display:none;">
            <span></span>
            <a href="" class="close">&times;</a>
        </div>
    </div>
</div>

grails-app/views/layouts/_footer.gsp
<!-- footer -->
<div class="row" id="footer">
    <div class="two columns col1">
        <h2>Get started</h2>
        <ul>
            <sec:ifLoggedIn>
                <li>Sign-in</li>
                <li>Sign-up</li>
            </sec:ifLoggedIn>
            <sec:ifNotLoggedIn>
                <li><a href="${createLink(controller:'login',action:'auth')}">Sign-in</a></li>
                <li><a href="${createLink(controller:'register',action:'index')}">Sign-up</a></li>
            </sec:ifNotLoggedIn>
        </ul>
    </div>
    <div class="two columns col2">
        <h2>Guides</h2>
        <ul>
            <li><a href="${createLink(controller:'general',action:'gettingStarted')}"><g:message code="gettingStarted.label"/></a></li>
            <li class="last"><a href="${createLink(controller:'general',action:'communityGuidelines')}"><g:message code="communityGuide.label"/></a></li>
            %{--<li><a href="${createLink(controller:'parentGuide')}">For Parents</a></li>--}%
            %{--<li><a href="#">For Teens & Tweens</a></li>--}%
            %{--<li class="last"><a href="${createLink(controller:'communityGuidelines')}">Community</a></li>--}%

        </ul>
    </div>
    <div class="two columns col3">
        <h2 id="footer_artworks">Artworks</h2>
        <ul>
            <li><a href="${createLink(controller:'register',action:'index')}">Open a Gallery</a></li>
            %{--<li><a href="${createLink(controller:'search',action:'searchItems')}">Find an Artist</a></li>--}%
            <li><a href="${createLink(controller:'search',action:'freshPaint')}">By Most Recent</a></li>
            <li><a href="${createLink(controller:'search',action:'typeAndAge')}">By Type & Age</a></li>
            <li class="last"><a href="${createLink(controller:'artwork',action:'emergingThemes')}">By Themes</a></li>
        </ul>
    </div>
    <div class="two columns col4">
        &nbsp;
    </div>
    <div class="two columns col5">
        <h2>
            <r:img uri="/images/logo_gog_footer.jpg"/>
        </h2>
        <p><g:message code="footer.copy.line1"/></p>
    </div>
    <div class="two columns col6">
        <h2>&nbsp;</h2>
        <ul>
            <li><a href="${createLink(controller:'general',action:'aboutUs')}">About Us</a></li>
            <li><a href="${createLink(controller:'general',action:'twoCents')}">2 Cents Circle</a></li>
            <li><a href="${createLink(controller:'general',action:'termsOfService')}">Terms of Service</a></li>
            <li><a href="${createLink(controller:'general',action:'privacyPolicy')}">Privacy Policy</a></li>
            <li class="last"><g:link controller="contactUs">Contact Us</g:link></li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="eight columns bottom-connect">
        Connect the dots: &nbsp;
        <a href="http://www.facebook.com/galleryofgood"><r:img uri="/images/ico-footer-facebook.png" alt="" /></a>
        <a href="http://www.pinterest.com/galleryofgood"><r:img uri="/images/ico-footer-pin.png" alt="" /></a>
        <a href="http://www.twitter.com/galleryofgood"><r:img uri="/images/ico-footer-twitter.png" alt="" /></a>
    </div>
    <div class="four columns"><p id="copyright">Gallery of Good Inc. &copy; 2012</p></div>
</div>
<!-- footer -->

grails-app/views/layouts/_header.gsp
<!-- header -->
<div class="row" id="header">
    <div class="two columns col1">
        <h1><a href="${createLink(uri: '/')}"><span>Gallery of Good&trade;</span></a></h1>
    </div>

    <div class="two columns col2">
        <h3>Keep Creating!</h3>
    </div>

    <div class="two columns col3">
        &nbsp;
    </div>

    <div class="two columns col4">
        &nbsp;
    </div>

    <div class="two columns col5">
        <ul>
            <sec:ifNotLoggedIn>
                <li><a href="${createLink(controller:'login',action:'auth')}">Sign-in</a></li>
                <li><a href="${createLink(controller:'register',action:'index')}">Sign-up</a></li>
            </sec:ifNotLoggedIn>
            <sec:ifLoggedIn>
                <li>Hello,</li>
                <li id="username"><a href="${createLink(controller:"appUser",action:"accountSettings")}"><sec:loggedInUserInfo field="username"/></a></li>
                <li class="last"><a href="${createLink(controller:'logout')}">Log-out</a></li>
            </sec:ifLoggedIn>
        </ul>
    </div>

    <div class="two columns col6">
        <ul>
            <li>Guides:</li>
            <li><a href="${createLink(controller:'general',action:'gettingStarted')}"><g:message code="gettingStarted.label"/></a></li>
            <li class="last"><a href="${createLink(controller:'general',action:'communityGuidelines')}"><g:message code="communityGuide.label"/></a></li>
        </ul>
    </div>
</div>
<!-- header -->

grails-app/views/layouts/_modalAlert.gsp
<div id="${elementId?:'modalAlert'}" class="reveal-modal modal-view">
    <p style="margin:0" id="alert-content">
    <g:if test="${flash.successMessage}">
        ${flash.successMessage}
    </g:if>
    </p>
    <a  style="margin:5px 0 0 0;" class="button small nice radius black" href="javascript:" onclick="$('.close-reveal-modal').click();">Okay</a>
    <a class="close-reveal-modal">×</a>
</div>
<div class="reveal-modal-bg modal-no-bg"></div>
<g:if test="${flash.successMessage}">
<script type="text/javascript">
    $('#${elementId?:'modalAlert'}').reveal({dismissModalClass: 'close-reveal-modal'});
</script>
</g:if>

grails-app/views/layouts/_modalConfirm.gsp
<r:require module="jqueryDirtyForms"/>
<div id="modalConfirm" class="reveal-modal modal-view" style="position:fixed">
    <p style="margin:0">
        You have unsaved changes. Are you sure you want to leave this page?
    </p>

    <div class="btn_grp" style="margin:15px 0 0 -10px;text-align: center">
        <a id="yes" class="ignoredirty continue nice small radius black button"
           style="width:110px;">Leave this page</a>
        <a id="no" class="ignoredirty cancel nice small radius red button close-reveal"
           style="width:130px;">Stay on this page</a>
        <a class="close-reveal-modal close-reveal close">×</a>
    </div>
</div>
<r:script type="text/javascript">
    $('form.custom').dirtyForms();
</r:script>

grails-app/views/layouts/_modalNotify.gsp
<div id="${elementId?:'modalNotify'}" class="reveal-modal modal-view">
    <p style="margin:0">
        ${flash.message?:content}
    </p>
    <g:if test="${content == "Please sign-in or sign-up to flag this artwork."}">
        <a  style="margin:5px 0 0 0;" class="button small nice radius black" href="${createLink(controller: 'general', action: 'artworkFlag', params: ['id':id, 'myModal':true])}">Sign-in</a>
    </g:if>
    <g:if test="${content == "Please sign-in or sign-up to flag this gallery."}">
        <a  style="margin:5px 0 0 0;" class="button small nice radius black" href="${createLink(controller: 'general', action: 'galleryFlag', params: ['galleryName':galleryName, 'myModal':true])}">Sign-in</a>
    </g:if>
    <g:if test="${content == "Please sign-in or sign-up to follow this gallery."}">
        <g:if test="${artworkId}">
            <a  style="margin:5px 0 0 0;" class="button small nice radius black" href="${createLink(controller: 'general', action: 'galleryFollow', params: ['galleryName':galleryName, 'artworkId':artworkId])}">Sign-in</a>
        </g:if>
        <g:else>
            <a  style="margin:5px 0 0 0;" class="button small nice radius black" href="${createLink(controller: 'general', action: 'galleryFollow', params: ['galleryName':galleryName])}">Sign-in</a>
        </g:else>
    </g:if>
    <a class="close-reveal-modal">×</a>
</div>
<div class="reveal-modal-bg modal-no-bg"></div>

<script type="text/javascript">
    <g:if test="${flash.message}">
    $('#modalNotify').reveal({dismissModalClass: 'close-reveal-modal'});
    </g:if>
    <g:if test="${flash.message}">
    $(function(){window.setTimeout(
            function() {
                $(".close-reveal-modal").click();
            },
            ${timeout?:'5000'}
    );})
    </g:if>
    $('.modal-show').click(function(){
        window.setTimeout(
                function() {
                    $(".close-reveal-modal").click();
                },
                ${timeout?:'5000'}
        );
    })
</script>

grails-app/views/layouts/_navigation.gsp
<!-- navigation -->
<g:if test="${sec.loggedInUserInfo(field: 'hasLoggedIn') == 'No'&&"You".equals(activeLink)}">
    <r:script>
        $(function() {
            jQuery.ajax({
			type:'GET',
			url:'${createLink(controller: 'register', action: 'updateFirstLogin')}',
			success:function(data, textStatus) {
            },
            error:function(XMLHttpRequest, textStatus, errorThrown) {
            }
		});
        });
    </r:script>
    <div class="row">
        <div class="twelve columns">
            <div id="tool-tip" class="alert-box">
                <r:img uri="/images/tool_tip_arrow.jpg" class="float-left"/>
                Here's where you manage your account settings.
                <br>
                Only you can see this when you log in.
                <a class="close" href="">×</a>
            </div>
        </div>
    </div>
</g:if>
<div class="row" id="navigation">
    <div class="twelve columns">
        <ul class="nav-bar">
            <sec:ifLoggedIn>
            <li id="you"><a href="${createLink(controller:'appUser',action:"accountSettings")}" class="${"You".equals(activeLink)?"current-page":""} navigate-header">You</a></li>
                <li id="artworks"><a class="navigate-header" href="${createLink(controller:'artwork',action:'landing')}">Artworks</a></li>
            %{--<li id="artworks"><a href="${createLink(controller:'gallery')}" class="${"Artworks".equals(activeLink)?"current-page":""}">Artworks</a></li>--}%
            </sec:ifLoggedIn>
            <sec:ifNotLoggedIn>
                <li id="artworks"><a href="${createLink(controller:'artwork',action:'landing')}">Artworks</a></li>
                <li></li>
            </sec:ifNotLoggedIn>
            <li></li>
            <li></li>
            %{--<li id="experiences"><a href="#">Experiences</a></li>--}%
            %{--<li id="fundraisers"><a href="#">Fundraisers</a></li>--}%
            <li>
                <div id="search-module">
                    <g:form controller="search" action="searchItems" class="custom" method="post">
                        <input name="searchKey" class="search-box" type="text" value="" placeholder="Search"/>
                        <g:select name="searchType" from="${['Artworks']}" value="${searchType?:"Artworks"}"/>
                        <g:submitButton name="submit" class="submit-button" type="submit" value=""/>
                        <div class="clear-both"></div>
                    </g:form>
                </div>
            </li>
        </ul>
    </div>
</div>
<!-- navigation -->

grails-app/views/layouts/_secondaryNavigation.gsp
<div class="row" id="secondary_navigation">
    <div class="twelve columns">
        <ul id="level-1">
            <li class="${activePage=='accountSettings'||activePage=='notificationSettings'?"selected":""}">
                <a href="${activePage=='accountSettings'?"#":createLink(controller:'appUser',action:'accountSettings')}">Account</a></li>
            <li class="${activePage in ['timeline','gallerySettings','artworks','guide']?"selected":""}"><a href="${createLink(controller:'gallery')}">Gallery</a></li>
            <li class="${activePage in ['comments','following','activityGuide']?"selected":""}"><a href="${createLink(controller:'activity')}">Activity</a></li>
            <!--li><a href="#">Goodworks</a></li-->
            <!--li><a href="#">Bids</a></li-->
        </ul>
        <div class="clear-both"></div>
        <g:if test="${activePage=='accountSettings'||activePage=='notificationSettings'}">
        <ul id="level-2">
            <li class="${activePage=='accountSettings'?"selected":""}"><a href="${activePage=='accountSettings'?"#":createLink(controller:'appUser',action:'accountSettings')}">Settings</a></li>
            <li class="${activePage=='notificationSettings'?"selected":""}"><a href="${activePage=='notificationSettings'?"#":createLink(controller:'appUser',action:'notificationSettings')}">Notifications</a></li>
        </ul>
        </g:if>
        <g:if test="${activePage in ['timeline','gallerySettings','artworks','guide']}">
            <ul id="level-2">
                <li class="${'gallerySettings'.equals(activePage)?'selected':''}"><a href="${createLink(controller:'gallery',action:'index')}">Settings</a></li>
                <li class="${'artworks'.equals(activePage)?'selected':''}"><a href="${createLink(controller:'artwork',action:'index')}">Artworks</a></li>
                <g:if test="${galleryInstance?.galleryNameUrl || gallery?.galleryNameUrl || artwork?.gallery}">
                    <g:if test="${galleryInstance?.artworks?.findAll{it.status=="Approved" && it.showInTimeline=="on"}?.size()>0 || gallery?.artworks?.findAll{it.status=="Approved" && it.showInTimeline=="on"}?.size()>0 || artwork?.gallery?.artworks?.findAll{it.status=="Approved" && it.showInTimeline=="on"}?.size()>0 }">
                        <li class="${'timeline'.equals(activePage)?'selected':''}"><a href="${createLink(controller:'gallery',action:'timeline')}">Artist Timeline</a></li>
                    </g:if>
                </g:if>
                <li class="${'guide'.equals(activePage)?'selected':''}"><a href="${createLink(controller:'gallery',action:'guide')}">Guide</a></li>
                <g:if test="${galleryInstance?.galleryNameUrl || gallery?.galleryNameUrl || artwork?.gallery}">
                    <g:if test="${galleryInstance?.artworks?.findAll{it.status=="Approved"}?.size()>0 || gallery?.artworks?.findAll{it.status=="Approved"}?.size()>0 || artwork?.gallery?.artworks?.findAll{it.status=="Approved"}?.size()>0 }"><li><a href="${createLink(controller:galleryInstance?.galleryNameUrl?:gallery?.galleryNameUrl)}">View</a></li>
                    </g:if>
                </g:if>
            </ul>
        </g:if>
        <g:if test="${activePage in ['comments','following','activityGuide']}">
            <ul id="level-2">
                <li class="${'comments'.equals(activePage)?'selected':''}"><a href="${createLink(controller:'activity',action:'comments')}">Comments</a></li>
                <li class="${'following'.equals(activePage)?'selected':''}"><a href="${createLink(controller:'activity',action:'following')}">Following</a></li>
                <li class="${'activityGuide'.equals(activePage)?'selected':''}"><a href="${createLink(controller:'activity',action:'activityGuide')}">Guide</a></li>

            </ul>
        </g:if>
    </div>
</div>

grails-app/views/layouts/adminmain.gsp
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="en"> <!--<![endif]-->
<head>
    <meta charset="utf-8" />
    <!-- Set the viewport width to device width for mobile -->
    <meta name="viewport" content="width=device-width" />
    <title><g:layoutTitle default="Gallery of Good Administration"/></title>
    <link rel="shortcut icon" href="${resource(dir:'images', file:'favicon.ico')}">
    <!-- Included CSS Files -->
    <r:require modules="core,foundation"/>
    <!--[if lt IE 9]>
		<link rel="stylesheet" href="stylesheets/ie.css">
	<![endif]-->
    <!-- IE Fix for HTML5 Tags -->
    <!--[if lt IE 9]>
		<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
    <r:layoutResources/>
</head>
<body>
<!-- container -->
<div class="container">

    <sec:ifLoggedIn>
<!-- header -->
<div class="row admin-panel" id="header">
    <div class="two columns col1">
        <h1><a href="#"><span>Gallery of Good&trade;</span></a></h1>
    </div>
    <div class="two columns col2"></div>
    <div class="two columns col3"></div>
    <div class="two columns col4"></div>
    <div class="two columns col5"></div>
    <div class="two columns col6">
        <a href="#"><sec:loggedInUserInfo field="username"/></a>
        |
        <a href="${createLink(controller:'logout')}">Logout</a>
    </div>
</div>
<!-- header -->
    </sec:ifLoggedIn>
<div class="row">
    <div class="twelve columns">&nbsp;</div>
</div>
<!-- main content area -->
<div class="row">
<g:render template="/layouts/adminmenu"/>
<g:layoutBody/>

</div>
<!-- main content area -->


</div>
<!-- container -->
<r:layoutResources/>
</body>
</html>

grails-app/views/layouts/main.gsp
<!doctype html xmlns:fb="http://ogp.me/ns/fb#">
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en" xmlns:fb="http://ogp.me/ns/fb#"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en" xmlns:fb="http://ogp.me/ns/fb#"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en" xmlns:fb="http://ogp.me/ns/fb#"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="en" xmlns:fb="http://ogp.me/ns/fb#"><!--<![endif]-->
<head>
    <meta charset="utf-8"/>
    <!-- Set the viewport width to device width for mobile -->
    <meta name="viewport" content="width=device-width"/>
    <newrelic:browserTimingHeader/>
    <link rel="shortcut icon" href="${resource(dir:'images', file:'favicon.ico')}">

    <title><g:layoutTitle default="Gallery of Good"/></title>
    <!-- Included CSS Files -->
    <r:require modules="core"/>

    <!--[if lt IE 9]>
		<!--<link rel="stylesheet" href="stylesheets/ie.css">-->
	<![endif]-->


    <!-- IE Fix for HTML5 Tags -->
    <!--[if lt IE 9]>
		<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
    <r:layoutResources/>

</head>

<body>
<div class="container">
    <g:render template="/layouts/header"/>
    <g:render template="/layouts/navigation" model="[activeLink:activeLink]"/>
    <g:layoutBody/>
    <g:render template="/layouts/footer"/>
</div>
<!-- container -->




<!-- Included JS Files -->
%{--<script src="javascripts/foundation.js"></script>--}%
%{--<script src="javascripts/app.js"></script>--}%
<r:layoutResources/>
<newrelic:browserTimingFooter/>
</body>
</html>

grails-app/views/layouts/register.gsp
<html>

<head>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Create your account - Gallery of Good</title>
    <g:layoutHead/>
</head>

<body>

%{--<g:javascript src='jquery/jquery.jgrowl.js'/>--}%
%{--<g:javascript src='jquery/jquery.checkbox.js'/>--}%
%{--<g:javascript src='spring-security-ui.js'/>--}%
<g:layoutBody/>

</body>
</html>