grails-app/domain/com/galleryofgood/common/SystemParameter.groovy
package com.galleryofgood.common

import com.galleryofgood.master.Base

class SystemParameter extends Base{

    String name;
    String content;

    static constraints = {

        name(inList:['AdminEmail','SupportEmail','ContactUsEmail'], maxSize:255)
        content(maxSize:255);

    }
}

grails-app/domain/com/galleryofgood/security/AppUser.groovy
package com.galleryofgood.security

import com.galleryofgood.user.UserDetails
import com.galleryofgood.master.Base
import com.galleryofgood.gallery.Gallery
import com.galleryofgood.common.Comment

class AppUser{

	transient springSecurityService

    static transients = ['role', 'galleryName', 'activity', 'flagged'];

    String id

	String username
	String password
    String email
    String lastName
    String firstName
	boolean enabled
	boolean accountExpired
	boolean accountLocked
	boolean passwordExpired

    Date dateCreated
    Date lastUpdated
    Date lastLoginDate
    
    
    //Additional User Details
    String ageGroup
    String optin
    String hasLoggedIn="No"
    String website
    

    static hasOne=[userDetails:UserDetails]

	static constraints = {
		username blank: false, unique: true
		password blank: false
        email unique:true,email:true
        lastName blank: true, nullable: true
        firstName blank: true, nullable: true
        ageGroup blank: true, nullable:true
        optin blank: true, nullable:true
        hasLoggedIn blank:true,nullable: true
        website blank:true,nullable:true,url: true
        lastLoginDate blank: true,nullable: true
	}

	static mapping = {
		password column: '`password`'
        id generator:'uuid'
	}

	Set<Role> getAuthorities() {
		AppUserRole.findAllByAppUser(this).collect { it.role } as Set
	}

	def beforeInsert() {
		encodePassword()
	}

	def beforeUpdate() {
		if (isDirty('password')) {
			encodePassword()
		}
	}

    String getRole(){
        String temp = ""
        this.getAuthorities().each{
                temp += "${it.description}";
        }
        return temp;
    }

    Long getActivity(){
        return Comment.countByUsername(this.username) as Long;
    }

    Long getFlagged(){
        return Gallery.findByOwner(this.username)?.artworks?.flags?.size()?:0 as Long;
    }

    String getGalleryName(){
        return Gallery.findByOwner(this.username).galleryName;
    }

	protected void encodePassword() {
		password = springSecurityService.encodePassword(password)
	}
}

grails-app/controllers/com/galleryofgood/common/SystemParameterController.groovy
package com.galleryofgood.common

class SystemParameterController {

    static allowedMethods = [save: "POST", update: "POST", delete: "POST"]

    def editParameters(){
        render view:'/systemParameters/systemParameters'
    }

    def saveParameters(){
        def parameters = params.name

        parameters.each{
            def aParam = SystemParameter.findOrCreateByName(it.key)
            aParam.setContent(it.value);
            aParam.save()
        }

        flash.message="System Parameters have been saved."

        redirect action:'editParameters'
    }
}

grails-app/views/systemParameters/systemParameters.gsp
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name='layout' content='adminmain'/>
    <title><g:message code='systemparameters.edit'/></title>
    <r:require modules="foundation"/>
</head>

<body>
<div class="ten columns ap-right">
    <g:form action="saveParameters" name='editSystemParameters' class="custom nice">

        <g:render template="/layouts/flashMessage"/>
        <g:render template="/layouts/flashErrors"/>
        <p class="ap-page">System Parameters</p>

        <div class="row">
            <div class="nine columns">
                &nbsp;
            </div>

            <div class="one column">
                <input type="submit" class="small blue button round" value="Save">
            </div>
        </div>
        <g:each in="${com.galleryofgood.common.SystemParameter.constraints.name.inList}" var="parameter">
            <div class="row">
                <div class="ten columns horizontal_fields">

                    <label for="name.${parameter}">${parameter}:</label>
                    <g:textField name="name.${parameter}"
                                 value="${com.galleryofgood.common.SystemParameter.findByName(parameter)?.content}"
                                 class="input-text"/>
                    %{--<g:hasErrors bean="${appUserInstance}" field="password">--}%
                    %{--<small class="error" style="margin:1px;"><g:renderErrors bean="${appUserInstance}"--}%
                    %{--field="password"/></small>--}%
                    %{--</g:hasErrors>--}%

                </div>
            </div>
        </g:each>

        <div class="row">
            <div class="nine columns">
                &nbsp;
            </div>

            <div class="one column">
                <input type="submit" class="small blue button round" value="Save">
            </div>
        </div>

    </g:form>
</div>

</body>